### ISSUE TITLE
Arctis Nova 7x compatibility

### ISSUE THREAD

**Issue by thertejada** [craigster1991/arctis-battery-win-app#16]
Hello, I have tried your app with Arctis Nova 7x and they do not appear. Is it possible to add them? Thank you very much for your time.

![image](https://user-images.githubusercontent.com/44103644/229313860-8790b0f8-1369-4346-8b10-e831f1fd64fd.png)

**Comment by padraigdoran** [comment]
Here are the Arctis Nova 7 details while you are at it

![image](https://user-images.githubusercontent.com/1016537/232098114-ac5c328d-e0a9-4344-b5a8-3f9f5e956d92.png)

**Comment by craigster1991** [comment]
Ive added these devices into the latest release :) https://github.com/craigster1991/arctis-battery-win-app/releases/tag/v0.2.1

**Comment by thertejada** [comment]
Hello!
Unfortunately, it doesn't work, I've been debugging and I've seen that there is a condition that expects attDevice?.usage !== 1 in device.js, the problem is that my Artix 7X devices reach usage 1 (I don't know why it appears three times either).

{
    vendorId: 4152,
    productId: 8710,
    path: '\\\\?\\hid#vid_1038&pid_2206&mi_03#8&11defc96&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'Arctis Nova 7X',
    release: 273,
    interface: 3,
    usagePage: 65472,
    usage: 1
  },
   {
    vendorId: 4152,
    productId: 8710,
    path: '\\\\?\\hid#vid_1038&pid_2206&mi_04#8&3a49aa5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'Arctis Nova 7X',
    release: 273,
    interface: 4,
    usagePage: 12,
    usage: 1
  },
  {
    vendorId: 4152,
    productId: 8710,
    path: '\\\\?\\hid#vid_1038&pid_2206&mi_05#8&27198e21&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'Arctis Nova 7X',
    release: 273,
    interface: 5,
    usagePage: 65280,
    usage: 1
  }
