### ISSUE TITLE
Data to write to HID device

### ISSUE THREAD

**Issue by GrzesiuS** [craigster1991/arctis-battery-win-app#17]
Hello,
I see you used some data to write to HID device write([0x06, 0x18]). It works only for headsets, but how can I get data for other devices like Aerox wireless mouse?

**Comment by craigster1991** [comment]
Unfortunately input devices like mice and keyboards are protected and you
can't pull the data from what I've seen without low level access (direct
driver interaction).

The input devices I've tried just crash the process completely when
attempting to read or write data.
