### ISSUE TITLE
please add Nova Pro Wireless

### ISSUE THREAD

**Issue by HollowDem0n** [craigster1991/arctis-battery-win-app#18]
could you please add the Nova Pro Wireless?
![Senza titolo](https://user-images.githubusercontent.com/129974293/230130610-054f5d0b-91b0-4c43-b63e-1b6308586c7c.png)

**Comment by cedricbrice** [comment]
Came here for this product too.

Any chance this can be added?

Can confirm the IDs
![image](https://github.com/craigster1991/arctis-battery-win-app/assets/8264825/41147dc8-0396-4d46-b3c9-37771e99f2a7)

**Comment by cedricbrice** [comment]
I figured this was not what you could be looking for to add the device id.

I went in powershell and used this command
`Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -match '^USB' } | Format-List`


And found this block:
![image](https://github.com/craigster1991/arctis-battery-win-app/assets/8264825/ac441575-c60e-4c49-aeb3-b2b26c535f6a)
suggesting the ID of the headset is 12E0 in hexadecimal which translates into 4832 in decimal.

**Comment by craigster1991** [comment]
Ive added this device into the latest release :) https://github.com/craigster1991/arctis-battery-win-app/releases/tag/v0.2.1
