### ISSUE TITLE
Add SteelSeries Arctis 1 Wireless Support

### ISSUE THREAD

**Issue by HypeGameMode** [craigster1991/arctis-battery-win-app#21]
I have the Steelseries Arctis 1 (Xbox Edition) and I would like to get a support from this app.
Here is the information the developer needs:
![image](https://github.com/craigster1991/arctis-battery-win-app/assets/81685371/66e62f33-2f60-446b-b625-36ef3ac10ba0)

**Comment by craigster1991** [comment]
Ive added this device into the latest release :) https://github.com/craigster1991/arctis-battery-win-app/releases/tag/v0.2.1
