### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by hajkenek** [craigster1991/arctis-battery-win-app#4]
Hi, I can't turn on application, I use Arctic 9, I seen the same problem with 9x somewhere on the internet. Can you add this model to application?
winver: 21H1 - 19043.1237

![image](https://user-images.githubusercontent.com/66490316/136428615-e49755ff-6d3f-4029-8ff6-ff622d1d4f10.png)

Thx for respond

**Comment by craigster1991** [comment]
Hello!
please see my updated app!
there's instructions on how to find the info I need if your device doesn't show up :)
