### ISSUE TITLE
[Request] Artic 7+wireless model support

### ISSUE THREAD

**Issue by Niggolo** [craigster1991/arctis-battery-win-app#5]
Hello man, i love this app and tbh those headphone should have that as default but nvm....
anyway it is possible to add support for the new model as well? i get that error
https://i.imgur.com/dx2U40w.png

**Comment by craigster1991** [comment]
Hey
Yeah I need to build some test apps to figure out why the arctis 9 isn't working. 
Hopefully I'll get some time soon to build and send to people with that headset (I only have the 7) to see what's going on
Appreciate the love though!

**Comment by Niggolo** [comment]
it is not artic 9, https://steelseries.com/gaming-headsets/arctis-7-plus, it is just an updated version of the model 7

**Comment by cele-matt** [comment]
If it helps I have an Arctis 7+ however looking up the VID and PID I get USB\VID_1038&PID_220E which is very different to other Arctis headsets however the format does seem similar to other steel series devices.

**Comment by viktorzenk** [comment]
Arctis 9 support would be greatly appreciated! I could help out with testing if you want :)

**Comment by maybejoe** [comment]
+1 for Arctis 7+ support

**Comment by Themivoc** [comment]
+1 +1 for the 7+ :)

**Comment by avielc** [comment]
can't emphasize enough how much this would be such a perfect addition to steelseries 7+ 
All the gratitude possible <3 Thank you for even coming up with it in the first place!

**Comment by craigster1991** [comment]
Hello!
please see my updated app!
there's instructions on how to find the info I need if your device doesn't show up :)

**Comment by Niggolo** [comment]
Gonna try it as soon I go back to home

**Comment by Niggolo** [comment]
headset are still not detected even not here
https://i.imgur.com/49mI5TA.png

**Comment by hynekhavel** [comment]
My Arctis 7+ (2022) not detected in both lists (main screen and popup): ![image](https://user-images.githubusercontent.com/7483021/223805552-82b31d92-b20d-48fd-ae59-e258ab6a0969.png)

**Comment by avielc** [comment]
Hi @craigster1991 
![image](https://user-images.githubusercontent.com/13572969/224106612-ad28387c-44fb-4d71-b259-13aa95ec6ffd.png)
Here is a screenshot of the new window, nothing appears there. (Using 7+)
![image](https://user-images.githubusercontent.com/13572969/224106808-119646e2-3c88-4792-bc4b-406c1283a28c.png)
Any ideas what else needs to be done? There are no instructions anywhere.

**Comment by electriceccentric** [comment]
I'm having the same issue with the same model, both screens say no devices detected. Would really love to get this app working!

**Comment by craigster1991** [comment]
Ive added this device into the latest release :) https://github.com/craigster1991/arctis-battery-win-app/releases/tag/v0.2.1

**Comment by Niggolo** [comment]
https://i.imgur.com/iZIwlCp.png

**Comment by Themivoc** [comment]
> Hi @craigster1991 - Thank you for the hard work. Unfortunately I still done see it
> 
> ![image](https://user-images.githubusercontent.com/13572969/264717818-21256f83-49e0-47c9-9db0-bf2dfb902eb4.png)
> 
> I don't know if it's relate dto an update that happened a while ago with fixing Arctis 7+ issue with needing to hard reset them to get them unstuck (started happening a while ago to me) Anyways, it's completely undetected in the app. Could it be I'm missing some crucial step?

Hi there, I face the same issue. Arctis 7+, Firmware 0.1.14.0, Windows 11.
![2023-08-31 20_24_00-SteelSeries GG](https://github.com/craigster1991/arctis-battery-win-app/assets/25888228/7d755543-2592-4f12-9a5f-45519bab83d2)
![2023-08-31 20_24_24-SteelSeries devices battery](https://github.com/craigster1991/arctis-battery-win-app/assets/25888228/365360c6-e7d4-49c2-b93c-d92c837dc672)

**Comment by Themivoc** [comment]
Update with v0.2.2: Now the device is at least shown in the "Dont see your device" list! So it improved, but is not yet working

![2023-09-01 21_38_55-SteelSeries devices battery](https://github.com/craigster1991/arctis-battery-win-app/assets/25888228/6844cdc3-7896-4dc2-b719-5af9f66de1d2)
![2023-09-01 21_39_07-SteelSeries devices battery](https://github.com/craigster1991/arctis-battery-win-app/assets/25888228/a27a0284-ea4e-4a2d-b792-6e7cf36ac6ed)

**Comment by avielc** [comment]
![image](https://github.com/craigster1991/arctis-battery-win-app/assets/13572969/c9a8b56d-cddc-4310-869f-3db3197412d2)
This looks pretty awesome, I actually see my deskmat too! 😄 
but yea, Arctis 7+ only appears here.

**Comment by maybejoe** [comment]
![image](https://github.com/craigster1991/arctis-battery-win-app/assets/95027409/544ba4b0-4d8f-4c5a-b24c-49b5df15348e)

**Comment by Niggolo** [comment]
yeah it is show in the list for me too
![2023-09-01_22-05_steel-series-battery_Eog55](https://github.com/craigster1991/arctis-battery-win-app/assets/1492661/974935eb-847f-4c25-bb2a-5ea630d6ac85)

**Comment by Vatroki** [comment]
![steel-series-battery_REms9FE6m2](https://github.com/craigster1991/arctis-battery-win-app/assets/66736859/3092cc2d-2a2c-4e8c-b28c-784b77e31d7b)
This is how it looks for me
